import type { PanelState } from "../state.js";
import { PLATFORMS } from "../../utils/platforms.js";
import { toSafeTaskFilename } from "../../utils/taskQueue.js";
import { formatDuration } from "../remainingTime.js";
import { escapeHtml as e, icon, logo, badge, translator, primaryButton, outputPath, presentCount } from "./shared.js";
import { runTiles } from "./tiles.js";

export function renderFinishedView(state: PanelState) {
  const t = translator(state), run = state.run, finished = run.outcome === "finished";
  const done = run.savedCount + run.skippedCount + run.failedCount, elapsed = Math.max(0, (run.endTime || Date.now()) - run.startTime);
  const needsLook = Array.from(run.results.entries()).filter(([, result]) => result.outcome === "failed" || result.outcome === "skipped-warning").sort(([aIndex, a], [bIndex, b]) => Number(b.outcome === "failed") - Number(a.outcome === "failed") || aIndex - bIndex);
  const present = presentCount(state), remaining = state.loadedTasks.length - present;
  const issues = needsLook.map(([index, result]) => {
    const failed = result.outcome === "failed", filename = toSafeTaskFilename(run.taskQueue[index]?.name || "image.png");
    const message = failed ? result.errorType === "download" && /timeout|timed out|no.*file|download/i.test(result.error || "") ? t("ui.downloadFailed", { retries: result.retries ?? run.maxRetries }) : result.error || "" : t("ui.warningSkipped");
    return `<div class="result-row"><span class="result-chip ${failed ? "failed" : "skipped"}"></span><div class="result-details"><span class="result-title"><span>${e(filename)}</span><span class="result-status ${failed ? "failed" : "skipped"}">${e(t(failed ? "ui.failed" : "ui.skipped"))}</span></span><span class="result-description">${e(message)}</span>${result.warningExcerpt ? `<span class="muted result-description">${e(result.warningExcerpt)}</span>` : ""}</div></div>`;
  }).join("");
  const halt = run.outcome === "halted" ? `<section class="halt-card" role="alert"><strong>${e(t("ui.haltedTitle"))}</strong><span>${e(run.haltReason)}</span>${run.haltErrorType === "folder" ? `<button type="button" class="small-button solid" data-action="allow-halted">${e(t("ui.allowAgain"))}</button>` : run.haltErrorType === "locked-url" ? `<button type="button" class="small-button" data-action="open-chat">${e(t("ui.openChat"))}</button>` : ""}</section>` : "";
  return `<header class="panel-header"><div class="topbar">${logo()}<span class="state-pill ${finished ? "finished" : run.outcome}">${finished ? icon("check", 11) : ""}${e(t(finished ? "ui.finished" : "ui.stopped"))}</span></div><div class="run-stat"><span class="finished-stat"><span class="finished-caption">${e(t(finished ? "ui.savedOn" : "ui.stoppedOn", { platform: PLATFORMS[run.platform].label }))}</span><span class="run-numbers"><span class="big-number">${run.savedCount}</span><span class="number-total">/ ${run.taskQueue.length}</span></span></span><span class="run-time"><span>${e(t("ui.totalTime", { time: formatDuration(elapsed) }))}</span><span>${e(t("ui.perImage", { time: done ? formatDuration(elapsed / done) : "—" }))}</span></span></div>${runTiles(state, t("ui.finishedTiles", { saved: run.savedCount, skipped: run.skippedCount, failed: run.failedCount }))}</header><main class="finished-main">${halt}${needsLook.length ? `<section class="needs-look" aria-label="${e(t("ui.needsLook", { count: needsLook.length }))}"><span class="overline">${e(t("ui.needsLook", { count: needsLook.length }))}</span><div class="card">${issues}</div></section>` : ""}<section class="session-kept card" aria-label="${e(t("ui.session"))}"><div class="session-kept-heading">${badge(run.platform, "medium")}<strong>${e(t(run.sessionUrl ? "ui.sessionKept" : "ui.noChatLink"))}</strong>${run.sessionUrl ? `<button type="button" class="small-button" data-action="copy-session">${e(t("ui.copyLink"))}</button>` : ""}</div>${run.sessionUrl ? `<span class="session-url-box">${e(run.sessionUrl)}</span>` : ""}</section><section class="output-card card" aria-label="${e(t("ui.output"))}"><span class="file-icon">${icon("folder", 16)}</span><div><span class="output-path">${e(outputPath(state))}</span><span class="result-description">${e(t("ui.filesPresent", { present, total: state.loadedTasks.length }))}</span></div></section></main><footer class="panel-footer">${primaryButton(t(remaining > 0 ? "ui.runRemaining" : "ui.allSaved", { count: remaining }), "rerun", remaining <= 0, true)}<div id="blockReason" class="footer-links"><button type="button" class="text-button" data-action="copy-log">${e(t("ui.copyLog"))}</button><button type="button" class="text-button" data-action="back-setup">${e(t("ui.backSetup"))}</button></div></footer>`;
}
